
dna = 'ATTCGATTATAAGCTCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATC'
'ATTCGATTATAAGCACTGATCGATCGATCGATCGATCGATGCTATCGTCGT'
'ATTCGATTATAAGCATCGATCACGATCTATCGTACGTATGCATATCGATATCGATCGTAGTC'
'ATTCGATTATAAGCACTATCGATGATCTAGCTACGATCGTAGCTGTA'
'ATTCGATTATAAGCACTAGCTAGTCTCGATGCATGATCAGCTTAGCTGATGATGCTATGCA'


# Begin
# Open file for reading
# Open file for writing
# for each line in file
# Find length of line
# subtract unwanted
# 
#
# End
